python3 principal_simulation.py --dropout None None 0.3 --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None None 0.5 --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None None 0.7 --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout 0.3 None None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout 0.5 None None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout 0.5 None None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout 0.3 0.3 0.3 --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout 0.3 0.3 None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None 0.3 0.3 --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None 0.3 None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None 0.5 None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
python3 principal_simulation.py --dropout None 0.7 None --coherency --epochs 30 --dataset_method random --model cao --dataset OBER
